complete -c kju -f -s c --description "Enqueue task to a channel"
complete -c kju -f -s h --description "Show help"
complete -c kju -f -s l --description "List queued tasks"
complete -c kju -f -s q --description "Quiet mode"
complete -c kju -f -s v --description "Show version"
